apply_cuts: true
clas12ana_particles: true

only_preselection_cuts: false
only_electron_quality_cuts: false

# Preselection cuts:
apply_preselection_cuts: true
apply_Vz_e_cuts: true
apply_Vz_cuts: true
apply_dVz_cuts: true
apply_DC_e_fiducial_cuts: true
apply_DC_fiducial_cuts: true

# Electron quality cuts:
apply_electron_quality_cuts: true
apply_Nphe_cut: true
apply_ECAL_SF_cuts: true
apply_ECAL_P_cuts: true
apply_ECAL_fiducial_cuts: true
apply_Electron_beta_cut: true

apply_chi2_cuts_1e_cut: true

apply_nucleon_cuts: true
apply_nucleon_PID_cuts: true
apply_CDEdgeCuts: true
apply_CDRegionCuts: true
apply_ProtonPIDCuts: true
apply_GhostTrackCuts: true
apply_charged_ECAL_veto: true
apply_neutral_ECAL_veto: false

apply_nucleon_physical_cuts: true
apply_nBeta_fit_cuts: false
apply_fiducial_cuts: false
apply_kinematical_cuts: false
apply_kinematical_weights: false
apply_nucleon_SmearAndCorr: false

apply_reaction_monitoring_cuts: false
apply_P_miss_in_QE_range_cuts: false
apply_E_miss_in_QE_range_cuts: false
apply_P_miss_in_MECandSRC_range_cuts: false
apply_E_miss_in_MECandSRC_range_cuts: false
apply_xB_in_QE_range_cuts: false
apply_theta_q_pCD_in_lower_FSI_range_cut: false

custom_cuts_naming: true
