//
// Created by Alon Sportes on 05/03/2026.
//

#ifdef RECOANALYZERHISTOGRAMS_H

// Include classes:
    #include "../framework/classes/Directories/Directories.cpp"
    #include "../framework/classes/hPlots/hPlot1D.cpp"
    #include "../framework/classes/hPlots/hPlot2D.cpp"
    #include "../framework/classes/hPlots/hsPlots.cpp"

    // Include structs:
    #include "../framework/structures/RecoAnalyzerSettings/AnalysisCutSettings.h"
    #include "../framework/structures/RecoAnalyzerSettings/HistogramSettings.h"

class AnalysisCutSettings;
class Directories;
struct HistogramSettings;

class RecoAnalyzerHistograms {
   public:
    hPlot1D hNphe_1e_cut_BC_FD;
    hPlot1D hNphe_1e_cut_AC_FD;
    hPlot1D hNphe_1p_FD;
    hPlot1D hNphe_1n_FD;
    hPlot1D hNphe_2p_FD;
    hPlot1D hNphe_pFDpCD_FD;
    hPlot1D hNphe_nFDpCD_FD;

    hPlot1D hChi2_Electron_FD;
    hPlot1D hChi2_Proton_CD;
    hPlot1D hChi2_Proton_FD;
    hPlot1D hChi2_Electron_1e_cut_FD;
    hPlot1D hChi2_Proton_1e_cut_CD;
    hPlot1D hChi2_Proton_1e_cut_FD;
    hPlot1D hChi2_Kplus_1e_cut_CD;
    hPlot1D hChi2_Kplus_1e_cut_FD;
    hPlot1D hChi2_Kminus_1e_cut_CD;
    hPlot1D hChi2_Kminus_1e_cut_FD;
    hPlot1D hChi2_piplus_1e_cut_CD;
    hPlot1D hChi2_piplus_1e_cut_FD;
    hPlot1D hChi2_piminus_1e_cut_CD;
    hPlot1D hChi2_piminus_1e_cut_FD;
    hPlot1D hChi2_deuteron_1e_cut_CD;
    hPlot1D hChi2_deuteron_1e_cut_FD;
    hPlot1D hChi2_Electron_1p_FD;
    hPlot1D hChi2_Proton_1p_CD;
    hPlot1D hChi2_Proton_1p_FD;
    hPlot1D hChi2_Electron_1n_FD;
    hPlot1D hChi2_Proton_1n_CD;
    hPlot1D hChi2_Proton_1n_FD;
    hPlot1D hChi2_Electron_2p_FD;
    hPlot1D hChi2_Proton_2p_CD;
    hPlot1D hChi2_Proton_2p_FD;
    hPlot1D hChi2_Electron_pFDpCD_FD;
    hPlot1D hChi2_Proton_pFDpCD_CD;
    hPlot1D hChi2_Proton_pFDpCD_FD;
    hPlot1D hChi2_Electron_nFDpCD_FD;
    hPlot1D hChi2_Proton_nFDpCD_CD;
    hPlot1D hChi2_Proton_nFDpCD_FD;

    hPlot1D hVx_Electron_1e_cut_FD;
    hPlot1D hVy_Electron_1e_cut_FD;
    hPlot1D hVz_Electron_1e_cut_FD;
    hPlot2D hVz_Electron_vs_P_e_1e_cut_FD;
    hPlot2D hVz_Electron_vs_Theta_e_1e_cut_FD;
    hPlot2D hVz_Electron_vs_Phi_e_1e_cut_FD;
    hPlot1D hVx_Proton_1e_cut_CD;
    hPlot1D hVx_Proton_1e_cut_FD;
    hPlot1D hVy_Proton_1e_cut_CD;
    hPlot1D hVy_Proton_1e_cut_FD;
    hPlot1D hVz_Proton_1e_cut_CD;
    hPlot1D hVz_Proton_1e_cut_FD;
    hPlot2D hVz_Proton_vs_P_p_1e_cut_FD;
    hPlot2D hVz_Proton_vs_Theta_p_1e_cut_FD;
    hPlot2D hVz_Proton_vs_Phi_p_1e_cut_FD;
    hPlot2D hVz_Proton_vs_P_p_1e_cut_CD;
    hPlot2D hVz_Proton_vs_Theta_p_1e_cut_CD;
    hPlot2D hVz_Proton_vs_Phi_p_1e_cut_CD;
    hPlot1D hVx_Kplus_1e_cut_CD;
    hPlot1D hVx_Kplus_1e_cut_FD;
    hPlot1D hVy_Kplus_1e_cut_CD;
    hPlot1D hVy_Kplus_1e_cut_FD;
    hPlot1D hVz_Kplus_1e_cut_CD;
    hPlot1D hVz_Kplus_1e_cut_FD;
    hPlot1D hVx_Kminus_1e_cut_CD;
    hPlot1D hVx_Kminus_1e_cut_FD;
    hPlot1D hVy_Kminus_1e_cut_CD;
    hPlot1D hVy_Kminus_1e_cut_FD;
    hPlot1D hVz_Kminus_1e_cut_CD;
    hPlot1D hVz_Kminus_1e_cut_FD;
    hPlot1D hVx_piplus_1e_cut_CD;
    hPlot1D hVx_piplus_1e_cut_FD;
    hPlot1D hVy_piplus_1e_cut_CD;
    hPlot1D hVy_piplus_1e_cut_FD;
    hPlot1D hVz_piplus_1e_cut_CD;
    hPlot1D hVz_piplus_1e_cut_FD;
    hPlot1D hVx_piminus_1e_cut_CD;
    hPlot1D hVx_piminus_1e_cut_FD;
    hPlot1D hVy_piminus_1e_cut_CD;
    hPlot1D hVy_piminus_1e_cut_FD;
    hPlot1D hVz_piminus_1e_cut_CD;
    hPlot1D hVz_piminus_1e_cut_FD;
    hPlot1D hVx_Deuteron_1e_cut_CD;
    hPlot1D hVx_Deuteron_1e_cut_FD;
    hPlot1D hVy_Deuteron_1e_cut_CD;
    hPlot1D hVy_Deuteron_1e_cut_FD;
    hPlot1D hVz_Deuteron_1e_cut_CD;
    hPlot1D hVz_Deuteron_1e_cut_FD;
    hPlot1D hdVx_Proton_FD_1e_cut;
    hPlot1D hdVy_Proton_FD_1e_cut;
    hPlot1D hdVz_Proton_FD_1e_cut;
    hPlot2D hdVz_Proton_vs_P_p_1e_cut_FD;
    hPlot2D hdVz_Proton_vs_Theta_p_1e_cut_FD;
    hPlot2D hdVz_Proton_vs_Phi_p_1e_cut_FD;
    hPlot1D hdVx_Proton_CD_1e_cut;
    hPlot1D hdVy_Proton_CD_1e_cut;
    hPlot1D hdVz_Proton_CD_1e_cut;
    hPlot2D hdVz_Proton_vs_P_p_1e_cut_CD;
    hPlot2D hdVz_Proton_vs_Theta_p_1e_cut_CD;
    hPlot2D hdVz_Proton_vs_Phi_p_1e_cut_CD;
    hPlot1D hdVx_Kplus_FD_1e_cut;
    hPlot1D hdVy_Kplus_FD_1e_cut;
    hPlot1D hdVz_Kplus_FD_1e_cut;
    hPlot1D hdVx_Kplus_CD_1e_cut;
    hPlot1D hdVy_Kplus_CD_1e_cut;
    hPlot1D hdVz_Kplus_CD_1e_cut;
    hPlot1D hdVx_Kminus_FD_1e_cut;
    hPlot1D hdVy_Kminus_FD_1e_cut;
    hPlot1D hdVz_Kminus_FD_1e_cut;
    hPlot1D hdVx_Kminus_CD_1e_cut;
    hPlot1D hdVy_Kminus_CD_1e_cut;
    hPlot1D hdVz_Kminus_CD_1e_cut;
    hPlot1D hdVx_piplus_FD_1e_cut;
    hPlot1D hdVy_piplus_FD_1e_cut;
    hPlot1D hdVz_piplus_FD_1e_cut;
    hPlot1D hdVx_piplus_CD_1e_cut;
    hPlot1D hdVy_piplus_CD_1e_cut;
    hPlot1D hdVz_piplus_CD_1e_cut;
    hPlot1D hdVx_piminus_FD_1e_cut;
    hPlot1D hdVy_piminus_FD_1e_cut;
    hPlot1D hdVz_piminus_FD_1e_cut;
    hPlot1D hdVx_piminus_CD_1e_cut;
    hPlot1D hdVy_piminus_CD_1e_cut;
    hPlot1D hdVz_piminus_CD_1e_cut;
    hPlot1D hdVx_Deuteron_FD_1e_cut;
    hPlot1D hdVy_Deuteron_FD_1e_cut;
    hPlot1D hdVz_Deuteron_FD_1e_cut;
    hPlot1D hdVx_Deuteron_CD_1e_cut;
    hPlot1D hdVy_Deuteron_CD_1e_cut;
    hPlot1D hdVz_Deuteron_CD_1e_cut;
    hPlot1D hdVx_1p;
    hPlot1D hdVy_1p;
    hPlot1D hdVz_1p;
    hPlot1D hdVx_1n;
    hPlot1D hdVy_1n;
    hPlot1D hdVz_1n;
    hPlot1D hdVx_2p;
    hPlot1D hdVy_2p;
    hPlot1D hdVz_2p;
    hPlot1D hdVx_pFDpCD;
    hPlot1D hdVy_pFDpCD;
    hPlot1D hdVz_pFDpCD;
    hPlot1D hdVx_pFD_pFDpCD;
    hPlot1D hdVy_pFD_pFDpCD;
    hPlot1D hdVz_pFD_pFDpCD;
    hPlot1D hdVx_pCD_pFDpCD;
    hPlot1D hdVy_pCD_pFDpCD;
    hPlot1D hdVz_pCD_pFDpCD;
    hPlot1D hdVx_nFDpCD;
    hPlot1D hdVy_nFDpCD;
    hPlot1D hdVz_nFDpCD;
    hPlot1D hdVx_pCD_nFDpCD;
    hPlot1D hdVy_pCD_nFDpCD;
    hPlot1D hdVz_pCD_nFDpCD;

    hPlot1D hSF_1e_cut_BC_FD;
    hPlot1D hSF_1e_cut_AC_FD;
    hPlot2D hSF_VS_P_e_1e_cut_BC_FD;
    hPlot2D hSF_VS_P_e_1e_cut_AC_FD;
    hPlot1D hSF_1p_FD;
    hPlot2D hSF_VS_P_e_1p_FD;
    hPlot1D hSF_1n_FD;
    hPlot2D hSF_VS_P_e_1n_FD;
    hPlot1D hSF_2p_FD;
    hPlot2D hSF_VS_P_e_2p_FD;
    hPlot1D hSF_pFDpCD_FD;
    hPlot2D hSF_VS_P_e_pFDpCD_FD;
    hPlot1D hSF_nFDpCD_FD;
    hPlot2D hSF_VS_P_e_nFDpCD_FD;
    hPlot2D hVcal_VS_EoP_1e_cut_BC_PCAL;
    hPlot2D hVcal_VS_EoP_1e_cut_AC_PCAL;
    hPlot2D hWcal_VS_EoP_1e_cut_BC_PCAL;
    hPlot2D hWcal_VS_EoP_1e_cut_AC_PCAL;
    hPlot2D hUcal_VS_EoP_1e_cut_BC_PCAL;
    hPlot2D hUcal_VS_EoP_1e_cut_AC_PCAL;
    hPlot2D hPCAL_acceptance_1e_cut;
    hPlot2D hVcal_VS_EoP_1p_PCAL;
    hPlot2D hWcal_VS_EoP_1p_PCAL;
    hPlot2D hVcal_VS_EoP_1n_PCAL;
    hPlot2D hWcal_VS_EoP_1n_PCAL;
    hPlot2D hVcal_VS_EoP_2p_PCAL;
    hPlot2D hWcal_VS_EoP_2p_PCAL;
    hPlot2D hVcal_VS_EoP_pFDpCD_PCAL;
    hPlot2D hWcal_VS_EoP_pFDpCD_PCAL;
    hPlot2D hVcal_VS_EoP_nFDpCD_PCAL;
    hPlot2D hWcal_VS_EoP_nFDpCD_PCAL;

    void InitializeNpheHistograms(const AnalysisCutSettings& cut_settings, const Directories& directories, const HistogramSettings& settings);
    void InitializeChi2Histograms(const Directories& directories, const HistogramSettings& settings);
    void InitializeSamplingFractionHistograms(const AnalysisCutSettings& cut_settings, const Directories& directories, const HistogramSettings& settings, double beamE);
    void InitializeEcalEdgeHistograms(const AnalysisCutSettings& cut_settings, const Directories& directories, const HistogramSettings& settings);
    void InitializeVertexHistograms(const Directories& directories, const HistogramSettings& settings);
    void InitializeMomentumThresholdHistograms(const Directories& directories, const HistogramSettings& settings, double beamE);
    hPlot1D hP_Kminus_1e_cut_CD;
    hPlot1D hP_Kminus_1e_cut_FD;
    hPlot1D hP_Kplus_1e_cut_CD;
    hPlot1D hP_Kplus_1e_cut_FD;
    hPlot1D hP_LnFD_APID_1e_cut_FD;
    hPlot1D hP_LnFD_APID_1e_cut_ZOOMOUT_FD;
    hPlot1D hP_LnFD_APIDandNS_1e_cut_FD;
    hPlot1D hP_LnFD_APIDandNS_1e_cut_ZOOMOUT_FD;
    hPlot1D hP_LnFD_BPID_1e_cut_FD;
    hPlot1D hP_LnFD_BPID_1e_cut_ZOOMOUT_FD;
    hPlot1D hP_LnFD_reco_APID_1e_cut_FD;
    hPlot1D hP_LnFD_reco_APID_1e_cut_FD_ZOOMIN;
    hPlot1D hP_LnFD_reco_APID_1e_cut_FD_ZOOMOUT;
    hPlot1D hP_LnFD_reco_BPID_1e_cut_FD;
    hPlot1D hP_LnFD_reco_BPID_1e_cut_FD_ZOOMIN;
    hPlot1D hP_LnFD_reco_BPID_1e_cut_FD_ZOOMOUT;
    hPlot1D hP_deuteron_1e_cut_CD;
    hPlot1D hP_deuteron_1e_cut_FD;
    hPlot1D hP_e_1e_cut_FD;
    hPlot1D hP_e_APID_1n_FD;
    hPlot1D hP_e_APID_1p_FD;
    hPlot1D hP_e_APID_2p_FD;
    hPlot1D hP_e_APID_nFDpCD_FD;
    hPlot1D hP_e_APID_pFDpCD_FD;
    hPlot1D hP_e_BPID_1n_FD;
    hPlot1D hP_e_BPID_1p_FD;
    hPlot1D hP_e_BPID_2p_FD;
    hPlot1D hP_e_BPID_nFDpCD_FD;
    hPlot1D hP_e_BPID_pFDpCD_FD;
    hPlot1D hP_e_reco_1e_cut_FD;
    hPlot1D hP_e_reco_1e_cut_FD_ZOOMIN;
    hPlot1D hP_nFD_APID_1e_cut_FD;
    hPlot1D hP_nFD_APID_1e_cut_ZOOMOUT_FD;
    hPlot1D hP_nFD_APID_1n;
    hPlot1D hP_nFD_APID_1n_ZOOMOUT;
    hPlot1D hP_nFD_APIDandNS_1e_cut_FD;
    hPlot1D hP_nFD_APIDandNS_1e_cut_ZOOMOUT_FD;
    hPlot1D hP_nFD_APIDandNS_1n;
    hPlot1D hP_nFD_APIDandNS_1n_ZOOMOUT;
    hPlot1D hP_nFD_BPID_1e_cut_FD;
    hPlot1D hP_nFD_BPID_1e_cut_ZOOMOUT_FD;
    hPlot1D hP_nFD_nFDpCD;
    hPlot1D hP_nFD_nFDpCD_ZoomOut;
    hPlot1D hP_nFD_reco_APID_1e_cut_FD;
    hPlot1D hP_nFD_reco_APID_1e_cut_FD_ZOOMIN;
    hPlot1D hP_nFD_reco_APID_1e_cut_FD_ZOOMOUT;
    hPlot1D hP_nFD_reco_BPID_1e_cut_FD;
    hPlot1D hP_nFD_reco_BPID_1e_cut_FD_ZOOMIN;
    hPlot1D hP_nFD_reco_BPID_1e_cut_FD_ZOOMOUT;
    hPlot1D hP_nL_APID_nFDpCD_FD;
    hPlot1D hP_nL_APIDandNS_nFDpCD_FD;
    hPlot1D hP_nL_nFDpCD;
    hPlot1D hP_nR_nFDpCD;
    hPlot1D hP_n_APID_1n_FD;
    hPlot1D hP_n_APID_1n_ZOOMOUT_FD;
    hPlot1D hP_n_APID_1p_FD;
    hPlot1D hP_n_APID_2p_FD;
    hPlot1D hP_n_APID_nFDpCD_FD;
    hPlot1D hP_n_APID_pFDpCD_FD;
    hPlot1D hP_n_APIDandNS_1n_FD;
    hPlot1D hP_n_APIDandNS_1n_ZOOMOUT_FD;
    hPlot1D hP_n_APIDandNS_nFDpCD_FD;
    hPlot1D hP_n_BPID_1n_FD;
    hPlot1D hP_n_BPID_1n_ZOOMOUT_FD;
    hPlot1D hP_n_BPID_1p_FD;
    hPlot1D hP_n_BPID_2p_FD;
    hPlot1D hP_n_BPID_nFDpCD_FD;
    hPlot1D hP_n_BPID_pFDpCD_FD;
    hPlot1D hP_n_Ph_APID_1n_FD;
    hPlot1D hP_n_Ph_BPID_1n_FD;
    hPlot1D hP_n_VN_APID_1n_FD;
    hPlot1D hP_n_VN_BPID_1n_FD;
    hPlot1D hP_pCD_nFDpCD;
    hPlot1D hP_pCD_pFDpCD;
    hPlot1D hP_pFD_APID_1p;
    hPlot1D hP_pFD_APIDandPS_1p;
    hPlot1D hP_pFD_pFDpCD;
    hPlot1D hP_pL_pFDpCD;
    hPlot1D hP_pR_pFDpCD;
    hPlot1D hP_p_1_2p;
    hPlot1D hP_p_1e_cut_CD;
    hPlot1D hP_p_1e_cut_FD;
    hPlot1D hP_p_2_2p;
    hPlot1D hP_p_APID_1n_CD;
    hPlot1D hP_p_APID_1n_FD;
    hPlot1D hP_p_APID_1p_CD;
    hPlot1D hP_p_APID_1p_FD;
    hPlot1D hP_p_APID_2p_CD;
    hPlot1D hP_p_APID_2p_FD;
    hPlot1D hP_p_APID_nFDpCD_CD;
    hPlot1D hP_p_APID_nFDpCD_FD;
    hPlot1D hP_p_APID_pFDpCD_CD;
    hPlot1D hP_p_APID_pFDpCD_FD;
    hPlot1D hP_p_APIDandPS_1p_CD;
    hPlot1D hP_p_APIDandPS_1p_FD;
    hPlot1D hP_p_APIDandPS_pFDpCD_FD;
    hPlot1D hP_p_BPID_1n_CD;
    hPlot1D hP_p_BPID_1n_FD;
    hPlot1D hP_p_BPID_1p_CD;
    hPlot1D hP_p_BPID_1p_FD;
    hPlot1D hP_p_BPID_2p_CD;
    hPlot1D hP_p_BPID_2p_FD;
    hPlot1D hP_p_BPID_nFDpCD_CD;
    hPlot1D hP_p_BPID_nFDpCD_FD;
    hPlot1D hP_p_BPID_pFDpCD_CD;
    hPlot1D hP_p_BPID_pFDpCD_FD;
    hPlot1D hP_p_reco_1e_cut_CD;
    hPlot1D hP_p_reco_1e_cut_CD_ZOOMIN;
    hPlot1D hP_p_reco_1e_cut_FD;
    hPlot1D hP_p_reco_1e_cut_FD_ZOOMIN;
    hPlot1D hP_ph_APID_1n_FD;
    hPlot1D hP_ph_APID_1p_FD;
    hPlot1D hP_ph_APID_2p_FD;
    hPlot1D hP_ph_APID_nFDpCD_FD;
    hPlot1D hP_ph_APID_pFDpCD_FD;
    hPlot1D hP_ph_BPID_1n_FD;
    hPlot1D hP_ph_BPID_1p_FD;
    hPlot1D hP_ph_BPID_2p_FD;
    hPlot1D hP_ph_BPID_nFDpCD_FD;
    hPlot1D hP_ph_BPID_pFDpCD_FD;
    hPlot1D hP_ph_reco_APID_1e_cut_FD;
    hPlot1D hP_ph_reco_APID_1e_cut_FD_ZOOMIN;
    hPlot1D hP_ph_reco_BPID_1e_cut_FD;
    hPlot1D hP_ph_reco_BPID_1e_cut_FD_ZOOMIN;
    hPlot1D hP_piminus_1e_cut_CD;
    hPlot1D hP_piminus_1e_cut_FD;
    hPlot1D hP_piminus_APID_1n_CD;
    hPlot1D hP_piminus_APID_1n_FD;
    hPlot1D hP_piminus_APID_1p_CD;
    hPlot1D hP_piminus_APID_1p_FD;
    hPlot1D hP_piminus_APID_2p_CD;
    hPlot1D hP_piminus_APID_2p_FD;
    hPlot1D hP_piminus_APID_nFDpCD_CD;
    hPlot1D hP_piminus_APID_nFDpCD_FD;
    hPlot1D hP_piminus_APID_pFDpCD_CD;
    hPlot1D hP_piminus_APID_pFDpCD_FD;
    hPlot1D hP_piminus_BPID_1n_CD;
    hPlot1D hP_piminus_BPID_1n_FD;
    hPlot1D hP_piminus_BPID_1p_CD;
    hPlot1D hP_piminus_BPID_1p_FD;
    hPlot1D hP_piminus_BPID_2p_CD;
    hPlot1D hP_piminus_BPID_2p_FD;
    hPlot1D hP_piminus_BPID_nFDpCD_CD;
    hPlot1D hP_piminus_BPID_nFDpCD_FD;
    hPlot1D hP_piminus_BPID_pFDpCD_CD;
    hPlot1D hP_piminus_BPID_pFDpCD_FD;
    hPlot1D hP_piminus_reco_1e_cut;
    hPlot1D hP_piminus_reco_1e_cut_CD;
    hPlot1D hP_piminus_reco_1e_cut_CD_ZOOMIN;
    hPlot1D hP_piminus_reco_1e_cut_FD;
    hPlot1D hP_piminus_reco_1e_cut_FD_ZOOMIN;
    hPlot1D hP_piminus_reco_1e_cut_ZOOMIN;
    hPlot1D hP_piplus_1e_cut_CD;
    hPlot1D hP_piplus_1e_cut_FD;
    hPlot1D hP_piplus_APID_1n_CD;
    hPlot1D hP_piplus_APID_1n_FD;
    hPlot1D hP_piplus_APID_1p_CD;
    hPlot1D hP_piplus_APID_1p_FD;
    hPlot1D hP_piplus_APID_2p_CD;
    hPlot1D hP_piplus_APID_2p_FD;
    hPlot1D hP_piplus_APID_nFDpCD_CD;
    hPlot1D hP_piplus_APID_nFDpCD_FD;
    hPlot1D hP_piplus_APID_pFDpCD_CD;
    hPlot1D hP_piplus_APID_pFDpCD_FD;
    hPlot1D hP_piplus_BPID_1n_CD;
    hPlot1D hP_piplus_BPID_1n_FD;
    hPlot1D hP_piplus_BPID_1p_CD;
    hPlot1D hP_piplus_BPID_1p_FD;
    hPlot1D hP_piplus_BPID_2p_CD;
    hPlot1D hP_piplus_BPID_2p_FD;
    hPlot1D hP_piplus_BPID_nFDpCD_CD;
    hPlot1D hP_piplus_BPID_nFDpCD_FD;
    hPlot1D hP_piplus_BPID_pFDpCD_CD;
    hPlot1D hP_piplus_BPID_pFDpCD_FD;
    hPlot1D hP_piplus_reco_1e_cut;
    hPlot1D hP_piplus_reco_1e_cut_CD;
    hPlot1D hP_piplus_reco_1e_cut_CD_ZOOMIN;
    hPlot1D hP_piplus_reco_1e_cut_FD;
    hPlot1D hP_piplus_reco_1e_cut_FD_ZOOMIN;
    hPlot1D hP_piplus_reco_1e_cut_ZOOMIN;
    hPlot1D hP_rel_mu_nFDpCD;
    hPlot1D hP_rel_mu_pFDpCD;
    hPlot1D hP_rel_nFDpCD;
    hPlot1D hP_rel_pFDpCD;
    hPlot1D hP_tot_minus_q_nFDpCD;
    hPlot1D hP_tot_minus_q_pFDpCD;
    hPlot1D hP_tot_mu_nFDpCD;
    hPlot1D hP_tot_mu_pFDpCD;
    hPlot1D hP_tot_nFDpCD;
    hPlot1D hP_tot_pFDpCD;
    hPlot2D hP_LnFD_vs_Theta_LnFD_reco_APID_1e_cut_FD;
    hPlot2D hP_LnFD_vs_Theta_LnFD_reco_BPID_1e_cut_FD;
    hPlot2D hP_e_vs_Theta_e_reco_1e_cut_FD;
    hPlot2D hP_nFD_vs_P_e_1n;
    hPlot2D hP_nFD_vs_P_e_ZoomOut_1n;
    hPlot2D hP_nFD_vs_P_e_ZoomOut_nFDpCD;
    hPlot2D hP_nFD_vs_P_e_nFDpCD;
    hPlot2D hP_nFD_vs_P_pCD_nFDpCD;
    hPlot2D hP_nFD_vs_Theta_nFD_reco_APID_1e_cut_FD;
    hPlot2D hP_nFD_vs_Theta_nFD_reco_BPID_1e_cut_FD;
    hPlot2D hP_nFD_vs_phi_e_1n;
    hPlot2D hP_nFD_vs_phi_e_ZoomOut_1n;
    hPlot2D hP_nFD_vs_phi_e_ZoomOut_nFDpCD;
    hPlot2D hP_nFD_vs_phi_e_nFDpCD;
    hPlot2D hP_nFD_vs_theta_e_1n;
    hPlot2D hP_nFD_vs_theta_e_ZoomOut_1n;
    hPlot2D hP_nFD_vs_theta_e_ZoomOut_nFDpCD;
    hPlot2D hP_nFD_vs_theta_e_nFDpCD;
    hPlot2D hP_nL_vs_P_nR_nFDpCD;
    hPlot2D hP_pFD_vs_P_pCD_pFDpCD;
    hPlot2D hP_pL_vs_P_pR_pFDpCD;
    hPlot2D hP_p_1_vs_P_p_2_2p;
    hPlot2D hP_p_vs_Theta_p_reco_1e_cut_CD;
    hPlot2D hP_p_vs_Theta_p_reco_1e_cut_FD;
    hPlot2D hP_ph_vs_Theta_ph_reco_APID_1e_cut_FD;
    hPlot2D hP_ph_vs_Theta_ph_reco_BPID_1e_cut_FD;
    hPlot2D hP_piminus_vs_Theta_piminus_reco_1e_cut_CD;
    hPlot2D hP_piminus_vs_Theta_piminus_reco_1e_cut_FD;
    hPlot2D hP_piplus_vs_Theta_piplus_reco_1e_cut_CD;
    hPlot2D hP_piplus_vs_Theta_piplus_reco_1e_cut_FD;
    hPlot2D hP_tot_minus_q_vs_P_tot_nFDpCD;
    hPlot2D hP_tot_minus_q_vs_P_tot_pFDpCD;
    hPlot2D hP_tot_minus_q_vs_q_nFDpCD;
    hPlot2D hP_tot_minus_q_vs_q_pFDpCD;
    hPlot2D hP_tot_mu_vs_P_rel_mu_nFDpCD;
    hPlot2D hP_tot_mu_vs_P_rel_mu_pFDpCD;
    hPlot2D hP_tot_vs_P_rel_nFDpCD;
    hPlot2D hP_tot_vs_P_rel_pFDpCD;
    hPlot2D hphi_nFD_vs_P_e_1n;
    hPlot2D hphi_nFD_vs_P_e_nFDpCD;
    hPlot2D hphi_nFD_vs_phi_e_1n;
    hPlot2D hphi_nFD_vs_phi_e_nFDpCD;
    hPlot2D hphi_nFD_vs_theta_e_1n;
    hPlot2D hphi_nFD_vs_theta_e_nFDpCD;
    hPlot2D htheta_nFD_vs_P_e_1n;
    hPlot2D htheta_nFD_vs_P_e_nFDpCD;
    hPlot2D htheta_nFD_vs_phi_e_1n;
    hPlot2D htheta_nFD_vs_phi_e_nFDpCD;
    hPlot2D htheta_nFD_vs_theta_e_1n;
    hPlot2D htheta_nFD_vs_theta_e_nFDpCD;
    TH2D* hP_e_vs_Theta_e_reco_All_int_1n = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_All_int_1p = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_All_int_nFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_All_int_pFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_DIS_1n = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_DIS_1p = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_DIS_nFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_DIS_pFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_MEC_1n = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_MEC_1p = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_MEC_nFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_MEC_pFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_QEL_1n = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_QEL_1p = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_QEL_nFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_QEL_pFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_RES_1n = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_RES_1p = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_RES_nFDpCD = nullptr;
    TH2D* hP_e_vs_Theta_e_reco_RES_pFDpCD = nullptr;
    TH2D* hP_nFD_APIDandNS_VS_W_1n = nullptr;
    TH2D* hP_nFD_APIDandNS_VS_W_DIS_1n = nullptr;
    TH2D* hP_nFD_APIDandNS_VS_W_MEC_1n = nullptr;
    TH2D* hP_nFD_APIDandNS_VS_W_QEL_1n = nullptr;
    TH2D* hP_nFD_APIDandNS_VS_W_RES_1n = nullptr;
    TH2D* hP_nFD_VS_W_DIS_nFDpCD = nullptr;
    TH2D* hP_nFD_VS_W_MEC_nFDpCD = nullptr;
    TH2D* hP_nFD_VS_W_QEL_nFDpCD = nullptr;
    TH2D* hP_nFD_VS_W_RES_nFDpCD = nullptr;
    TH2D* hP_nFD_VS_W_nFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_DIS_nFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_DIS_pFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_MEC_nFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_MEC_pFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_QEL_nFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_QEL_pFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_RES_nFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_RES_pFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_nFDpCD = nullptr;
    TH2D* hP_pCD_VS_W_pFDpCD = nullptr;
    TH2D* hP_pFD_APIDandPS_VS_W_1p = nullptr;
    TH2D* hP_pFD_APIDandPS_VS_W_DIS_1p = nullptr;
    TH2D* hP_pFD_APIDandPS_VS_W_MEC_1p = nullptr;
    TH2D* hP_pFD_APIDandPS_VS_W_QEL_1p = nullptr;
    TH2D* hP_pFD_APIDandPS_VS_W_RES_1p = nullptr;
    TH2D* hP_pFD_VS_W_DIS_pFDpCD = nullptr;
    TH2D* hP_pFD_VS_W_MEC_pFDpCD = nullptr;
    TH2D* hP_pFD_VS_W_QEL_pFDpCD = nullptr;
    TH2D* hP_pFD_VS_W_RES_pFDpCD = nullptr;
    TH2D* hP_pFD_VS_W_pFDpCD = nullptr;
    std::string hP_e_vs_Theta_e_reco_1n_Dir;
    std::string hP_e_vs_Theta_e_reco_1p_Dir;
    std::string hP_e_vs_Theta_e_reco_nFDpCD_Dir;
    std::string hP_e_vs_Theta_e_reco_pFDpCD_Dir;
    std::string hP_nFD_APIDandNS_VS_W_1n_Dir;
    std::string hP_nFD_VS_W_nFDpCD_Dir;
    std::string hP_pCD_VS_W_nFDpCD_Dir;
    std::string hP_pCD_VS_W_pFDpCD_Dir;
    std::string hP_pFD_APIDandPS_VS_W_1p_Dir;
    std::string hP_pFD_VS_W_pFDpCD_Dir;
};

#endif  // RECOANALYZERHISTOGRAMS_H
