//
// Created by Alon Sportes on 23/12/2023.
//

// #ifndef CUSTOMPLOTSDIRECTORY_H
// #define CUSTOMPLOTSDIRECTORY_H
#ifdef CUSTOMPLOTSDIRECTORY_H

    #include <iostream>

    // Include libraries:
    #include "../../namespaces/setup/path_definitions.h"

/**
 * @class CustomPlotsDirectory
 * @brief A class for configuring custom plot directories based on various cut configurations.
 * @details The CustomPlotsDirectory class provides functionality for configuring custom plot directories based on various cut configurations. It includes member variables for storing
 * different path components and status strings related to the cuts applied in the analysis. The ConfigureStatuses function can be used to set the status strings based on the cuts applied,
 * while the SetPaths function can be used to construct the custom plot directory paths based on the working directory, sample name, and cut configurations. The class also includes getter
 * functions to retrieve the configured paths and status strings. By using this class, it allows for more organized and structured storage of plots based on the specific cut configurations
 * applied in the analysis, making it easier to manage and access the generated plots.
 * @note The implementation of the ConfigureStatuses and SetPaths functions will depend on the specific cut configurations and naming conventions used in the analysis, and should be designed
 * to ensure that the generated paths are consistent and meaningful. It is also important to ensure that the paths generated by the SetPaths function are valid and accessible, and that any
 * necessary directories are created if they do not already exist. Additionally, the status strings should be designed to provide clear and concise information about the cuts applied, making
 * it easier for developers to understand the analysis configuration at a glance when looking at the generated plot directories. Proper documentation of the class and its member functions is
 * also important to ensure that other developers can easily understand and utilize the functionality provided by the CustomPlotsDirectory class.
 */
class CustomPlotsDirectory {
   private:
    std::string Plots_path;
    std::string Run_dir_name;
    std::string Plots_log_save_Directory;
    std::string Skipped_files_list_save_Directory;

    std::string Stage0_prefix = "_S00_NO_CUTS";  // Stage 0 - no cuts
    std::string Stage1_prefix = "_S01ACwoChi2";  // Stage 1 - with cuts except PID (chi2) cuts
    std::string Stage2_prefix = "_S02AC";        // Stage 2 - set nucleon cuts (neutron beta fit & proton double detection cuts)
    std::string Stage3_prefix = "_S03AC";        // Stage 3 - other runs

    /* Save plots to custom-named folders, to allow multi-sample runs at once. */
    bool Custom_cuts_naming = true;
    std::string Clas12ana_particles_status = "", Preselection_Cuts_Status = "", Electron_Quality_Cuts_Status = "";

    std::string Nucleon_Cuts_Status = "", FD_photons_Status = "", PSmearing_Status = "", FiducialCuts_Status = "";
    std::string KinCuts_Status = "", KinWei_Status = "", Additional_Status = "", Efficiency_Status = "";

    std::string Added_PreStatuses, Added_Statuses;

    std::string Global_Run_Status = path_definitions::custom_plots_path_prefix;

   public:
    // Default constructor ---------------------------------------------------------------------------------------------------------------------------------------------

    CustomPlotsDirectory() = default;

    // ConfigureStatuses function ------------------------------------------------------------------------------------------------------------------------------------

    void ConfigureStatuses(const bool& apply_cuts, const bool& clas12ana_particles, const bool& only_preselection_cuts, const bool& apply_chi2_cuts_1e_cut,
                           const bool& only_electron_quality_cuts, const bool& apply_nucleon_cuts, const bool& Enable_FD_photons, const bool& apply_nucleon_SmearAndCorr,
                           const bool& apply_kinematical_cuts, const bool& apply_kinematical_weights, const bool& apply_fiducial_cuts, const bool& Generate_AMaps,
                           const bool& plot_and_fit_MomRes, const bool& VaryingDelta, const bool& Calculate_momResS2, const bool& Run_in_momResS2, const bool& nRes_test,
                           const bool& Rec_wTL_ES, const bool& ZoomIn_On_mom_th_plots);

    // SetPaths function -----------------------------------------------------------------------------------------------------------------------------------------------

    void SetPaths(const std::string& WorkingDirectory, const std::string& SampleName, const std::string& plots_path, const bool& apply_cuts, const bool& apply_chi2_cuts_1e_cut,
                  const bool& apply_nucleon_cuts);

    // Set functions ---------------------------------------------------------------------------------------------------------------------------------------------------

    void SetCustomCutsNaming(const bool& custom_cuts_naming) { Custom_cuts_naming = custom_cuts_naming; }

    // Get functions ---------------------------------------------------------------------------------------------------------------------------------------------------

    bool GetCustomCutsNaming() { return Custom_cuts_naming; }

    void GetPlotsPath(string& plots_path) {
        if (Custom_cuts_naming) { plots_path = Plots_path; }
    }

    std::string GetRun_dir_name() const { return Run_dir_name; }

    void GetPlotsLogSaveDirectory(string& plots_log_save_Directory) {
        if (Custom_cuts_naming) { plots_log_save_Directory = Plots_log_save_Directory; }
    }

    void GetSkippedHipoFilesLogSaveDirectory(string& skipped_files_list_save_Directory) {
        if (Custom_cuts_naming) { skipped_files_list_save_Directory = Skipped_files_list_save_Directory; }
    }

    std::string GetPreselection_Cuts_Status() { return Preselection_Cuts_Status; }

    std::string GetElectron_Quality_Cuts_Status() { return Electron_Quality_Cuts_Status; }

    std::string GetNucleon_Cuts_Status() { return Nucleon_Cuts_Status; }

    std::string GetFD_photons_Status() { return FD_photons_Status; }

    std::string GetPSmearing_Status() { return PSmearing_Status; }

    std::string GetFiducialCuts_Status() { return FiducialCuts_Status; }

    std::string GetKinWei_Status() { return KinWei_Status; }

    std::string GetAdditional_Status() { return Additional_Status; }

    std::string GetEfficiency_Status() { return Efficiency_Status; }
};

#endif  // CUSTOMPLOTSDIRECTORY_H
